FurnitureStore/Controllers/FurnitureController.cs
using FurnitureStore.Abstract;
using FurnitureStore.Concrete;
using FurnitureStore.Entities;
using FurnitureStore.Models;
using FurnitureStore.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureStore.Controllers
{
    public class FurnitureController : Controller
    {
        DataBaseEntity context = new DataBaseEntity();
        private IFurnitureRepo repository;
        public int pageSize = 9;

        public FurnitureController(IFurnitureRepo repo)
        {
            repository = repo;
        }
        
        
        public ViewResult List(string category, int page = 1)
        {
          
           ListViewModel model = new ListViewModel
             {
                 Furnitures = repository.Furnitures
                 .Where(p => category == null || p.Category.Name== category)
                 .OrderBy(f => f.FurnitureId)
                 .Skip((page - 1) * pageSize)
                 .Take(pageSize).ToList() , 
                 InfoPages = new InfoPage
                 {
                     CurrentPage = page,
                     ItemsPerPage = pageSize,
                     TotalItems =  category == null  ?  repository.Furnitures.Count() :
                     repository.Furnitures.Where(furniture => furniture.Category.Name == category).Count()
                 },
                 CurrentCategory = category
             };

            return View(model);
        }


      





        public ActionResult Details(int id) 
        {
            var furniture = repository.Details(id);
            IEnumerable<FurnitureImages> images = furniture.Images;
            FurnitureImages mainImage = images.Where(x => x.IsMainImage).FirstOrDefault();
            IEnumerable<FurnitureImages> secondaryImages = images.Where(x => !x.IsMainImage);

            Category categories = furniture.Category;

            FurnitureVM model = new FurnitureVM
            {
              
                Name = furniture.Name,
                Description = furniture.Description , 
                Manufacturer = furniture.Manufacturer , 
                Price = furniture.Price , 
                IsAvailable = furniture.IsAvailable ,
                Size = furniture.Size , 
                CategoryId = furniture.CategoryId ,

                MainImage = new ImageVM
                {
                    Id = mainImage.Id,
                    Path = mainImage.Path,
                    DisplayName = mainImage.DisplayName,
                    IsMainImage = mainImage.IsMainImage

                },

                Category = new CategoryVM
                {
                    Name = categories.Name
                },

                SecondaryImages = secondaryImages.Select(x => new ImageVM()
                {
                    Id = x.Id,
                    Path = x.Path,
                    DisplayName = x.DisplayName
                }).ToList()
            
        };

            return View(model);
        }


        public PartialViewResult SimilarProducts(string category)
        {
         


            ListViewModel model = new ListViewModel
            {
                Furnitures = repository.Furnitures
               .Where(x => category == null ? true : x.Category.Name.Equals(category))
                .OrderBy(r => Guid.NewGuid()).Take(5) , 

            
            };
            return PartialView(model);
            
        }

        public FileResult GetImage(int categoryId)
        {
            Category category = repository.Categories
                .FirstOrDefault(g => g.CategoryId == categoryId);

            if (category != null)
            {
                return File(category.ImageData, category.ImageMimeType);
            }
            else
            {
                return null;
            }
        }



        public JsonResult Search(string term)
        {
           // var data = context.Furnitures.Where(p => p.Name.StartsWith(term))
               // .Select(p => new { p.FurnitureId, p.Name }).ToList();

            var test = context.FurnitureImages.Where(p => p.IsMainImage == true).
                Join(context.Furnitures.Where(p => p.Name.Contains(term)),
                o => o.FurnitureId, od => od.FurnitureId,
                (o, od) => new
                {
                    od.FurnitureId,
                    od.Name,
                    od.Price,
                    o.Path
                }).Select(

                p => new
                {

                    p.FurnitureId , 
                    p.Price,
                    p.Name , 
                    p.Path,
                    
                })
                .ToList();


            return Json(test, JsonRequestBehavior.AllowGet);
            
        }
     }
}

FurnitureStore/Controllers/MenuAdminController.cs
using FurnitureStore.Abstract;
using FurnitureStore.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureStore.Controllers
{

    [Authorize(Roles = "admin")]
    public class MenuAdminController : Controller
    {
        IFurnitureRepo repo;


        public MenuAdminController(IFurnitureRepo repo)
        {
            this.repo = repo;
        }


        // GET: MenuAdmin
        public ViewResult Index()
        {
            return View(repo.Categories);
        }


        public ViewResult Edit(int categoryId)
        {
            Category category = repo.Categories
                    .FirstOrDefault(f => f.CategoryId == categoryId);
            return View(category);
               
        }


        [HttpPost]
        public ActionResult Edit(Category category , HttpPostedFileBase image = null)
        {
           
            if(ModelState.IsValid)
            {
                var updateImage = false;
                if (image != null)
                {
                    updateImage = true;
                 
                    category.ImageMimeType = image.ContentType;
                    category.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(category.ImageData, 0, image.ContentLength);
                }
                repo.SaveCategory(category, updateImage);
                TempData["message"] = string.Format("Changes in \"{0}\" has been saved", category.Name);
                return RedirectToAction("Index");
            }else
            {
               
                return View(category);
            }
        }


        public ViewResult Create()
        {
            return View("Edit", new Category());
        }


        [HttpPost]
        public ActionResult Delete(int categoryId)
        {
            Category deleteCategory = repo.DeleteCategory(categoryId);

            if(deleteCategory != null)
            {
                TempData["message"] = string.Format("Розділ менб\"{0}\" був успішно видалений",
                    deleteCategory.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

FurnitureStore/Views/MenuAdmin/Edit.cshtml
@model FurnitureStore.Entities.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="panel">
    <div class="panel-heading">
        <h3>Редагування меню @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "MenuAdmin",
                        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.CategoryId)

            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CategoryId":
                    case "ImageData":
                    case "ImageMimeType":
                    case "Furnitures":

                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>



                            @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })

                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Виберіть файл...
                        <input id="imgInp" type="file" name="Image"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>

                    <span class='label label-info' id="upload-file-info"></span>
                    <img id="blah" src="#" alt="your image" style="border-radius:2px;" />
                </div>
                @if (Model.ImageData == null)
                {
                   
                    <div class="form-control-static">Нема картинки</div>
                }
                else
                {

                    <img src="@Url.Action("GetImage", "Furniture",
                        new { Model.CategoryId })" />
                }






            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Збергети" class="btn btn-primary" />
            @Html.ActionLink("Повернутись до списку", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

FurnitureStore/Views/MenuAdmin/Index.cshtml
@model IEnumerable<FurnitureStore.Entities.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { categoryId = item.CategoryId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CategoryId }) |
           


            @using (Html.BeginForm("Delete", "MenuAdmin" , new { categoryId = item.CategoryId }))
            {
                @Html.Hidden("CategoryId)", item.CategoryId)
                <input type="submit"
                       class="btn btn-default btn-xs"
                       value="Видалити" />
            }
        </td>
    </tr>
}

</table>