FurnitureStore/Entities/Furniture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FurnitureStore.Entities
{
    public class Furniture
    {
     
      
        [Key]
        public int FurnitureId { get; set; }

        [Display(Name = "Назва")]
        [Required(ErrorMessage = "Будь ласка, введіть назву товару")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Опис")]
        [Required(ErrorMessage = "Будь ласка, введіть опис для даного товару")]
        public string Description { get; set; }
        [Display(Name = "Ціна (грн)")]
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Введіть додаткове значення для цього поля")]
        public decimal Price { get; set; }

        [Display(Name = "Виробник")]
        [Required(ErrorMessage = "Будь ласка, введіть назву виробника для даного товару")]
        public string Manufacturer { get; set; }
        [Display(Name = "Розмір")]
        [Required(ErrorMessage = "Будь ласка, введіть розмір для даного товару")]
        public string Size { get; set; }

        [Display(Name = "Категорія")]
        [Required]
        public int CategoryId { get; set; }
      
        public virtual Category Category { get; set; }


        [NotMapped]
        public virtual FurnitureImages Image { get; set; }

        public virtual ICollection<FurnitureImages> Images { get; set; }

        [Display(Name = "Чи присутній товар на складі")]
        public bool IsAvailable { get; set; }
    }
}

FurnitureStore/Controllers/FurnitureController.cs
using FurnitureStore.Abstract;
using FurnitureStore.Concrete;
using FurnitureStore.Entities;
using FurnitureStore.Models;
using FurnitureStore.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureStore.Controllers
{
    public class FurnitureController : Controller
    {
        DataBaseEntity context = new DataBaseEntity();
        private IFurnitureRepo repository;
        public int pageSize = 9;

        public FurnitureController(IFurnitureRepo repo)
        {
            repository = repo;
        }
        
        
        public ViewResult List(string category, int page = 1)
        {
          
           ListViewModel model = new ListViewModel
             {
                 Furnitures = repository.Furnitures
                 .Where(p => category == null || p.Category.Name== category)
                 .OrderBy(f => f.FurnitureId)
                 .Skip((page - 1) * pageSize)
                 .Take(pageSize).ToList() , 
                 InfoPages = new InfoPage
                 {
                     CurrentPage = page,
                     ItemsPerPage = pageSize,
                     TotalItems =  category == null  ?  repository.Furnitures.Count() :
                     repository.Furnitures.Where(furniture => furniture.Category.Name == category).Count()
                 },
                 CurrentCategory = category
             };

            return View(model);
        }


      





        public ActionResult Details(int id) 
        {
            var furniture = repository.Details(id);
            IEnumerable<FurnitureImages> images = furniture.Images;
            FurnitureImages mainImage = images.Where(x => x.IsMainImage).FirstOrDefault();
            IEnumerable<FurnitureImages> secondaryImages = images.Where(x => !x.IsMainImage);

            Category categories = furniture.Category;

            FurnitureVM model = new FurnitureVM
            {
              
                Name = furniture.Name,
                Description = furniture.Description , 
                Manufacturer = furniture.Manufacturer , 
                Price = furniture.Price , 
                IsAvailable = furniture.IsAvailable ,
                Size = furniture.Size , 
                CategoryId = furniture.CategoryId ,

                MainImage = new ImageVM
                {
                    Id = mainImage.Id,
                    Path = mainImage.Path,
                    DisplayName = mainImage.DisplayName,
                    IsMainImage = mainImage.IsMainImage

                },

                Category = new CategoryVM
                {
                    Name = categories.Name
                },

                SecondaryImages = secondaryImages.Select(x => new ImageVM()
                {
                    Id = x.Id,
                    Path = x.Path,
                    DisplayName = x.DisplayName
                }).ToList()
            
        };

            return View(model);
        }


        public PartialViewResult SimilarProducts(string category)
        {
         


            ListViewModel model = new ListViewModel
            {
                Furnitures = repository.Furnitures
               .Where(x => category == null ? true : x.Category.Name.Equals(category))
                .OrderBy(r => Guid.NewGuid()).Take(5) , 

            
            };
            return PartialView(model);
            
        }

        public FileResult GetImage(int categoryId)
        {
            Category category = repository.Categories
                .FirstOrDefault(g => g.CategoryId == categoryId);

            if (category != null)
            {
                return File(category.ImageData, category.ImageMimeType);
            }
            else
            {
                return null;
            }
        }



        public JsonResult Search(string term)
        {
           // var data = context.Furnitures.Where(p => p.Name.StartsWith(term))
               // .Select(p => new { p.FurnitureId, p.Name }).ToList();

            var test = context.FurnitureImages.Where(p => p.IsMainImage == true).
                Join(context.Furnitures.Where(p => p.Name.Contains(term)),
                o => o.FurnitureId, od => od.FurnitureId,
                (o, od) => new
                {
                    od.FurnitureId,
                    od.Name,
                    od.Price,
                    o.Path
                }).Select(

                p => new
                {

                    p.FurnitureId , 
                    p.Price,
                    p.Name , 
                    p.Path,
                    
                })
                .ToList();


            return Json(test, JsonRequestBehavior.AllowGet);
            
        }
     }
}

FurnitureStore/Controllers/FurnituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FurnitureStore.Concrete;
using FurnitureStore.Entities;
using FurnitureStore.Abstract;
using System.IO;
using FurnitureStore.ModelView;

namespace FurnitureStore.Controllers
{
    [Authorize(Roles = "admin")]
    public class FurnituresController : Controller
    {
        private DataBaseEntity db = new DataBaseEntity();

        IFurnitureRepo repo;


        public FurnituresController(IFurnitureRepo repo)
        {
            this.repo = repo;
        }




       
        public ActionResult Index()
        {
            var furnitures = db.Furnitures.Include(f => f.Category);
            return View(furnitures.ToList());
        }

        // GET: Furnitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Furniture furniture = db.Furnitures.Find(id);
            if (furniture == null)
            {
                return HttpNotFound();
            }
            return View(furniture);
        }



        // GET: Furnitures/Create
        public ActionResult Create()
        {

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View(new FurnitureVM());

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FurnitureVM model)
        {

            if (model.MainFile != null && model.MainFile.ContentLength > 0)
            {
                string displayName = model.MainFile.FileName;
                string extension = Path.GetExtension(displayName);
                string fileName = string.Format("{0}{1}", Guid.NewGuid(), extension);
                string path = "/Upload/" + fileName;
                model.MainFile.SaveAs(Server.MapPath(path));
                model.MainImage = new ImageVM() { Path = path, DisplayName = displayName };
            }

            foreach (HttpPostedFileBase file in model.SecondaryFiles)
            {

                if (file != null && file.ContentLength > 0)
                {
                    string displayName = file.FileName;
                    string extension = Path.GetExtension(displayName);
                    string fileName = string.Format("{0}{1}", Guid.NewGuid(), extension);
                    var path = "/Upload/" + fileName;
                    file.SaveAs(Server.MapPath(path));
                    model.SecondaryImages.Add(new ImageVM { Path = path, DisplayName = displayName });
                }
            }

             // FurnitureImages main = furniture.Images.Where(x => x.IsMainImage).FirstOrDefault();

            FurnitureImages images = new FurnitureImages();
            Furniture furniture = new Furniture
            {
                Name = model.Name,
                Description = model.Description,
                Size = model.Size,
                Price = model.Price,
                IsAvailable = model.IsAvailable,
                Manufacturer = model.Manufacturer,
                CategoryId = model.CategoryId,                 
            };


            db.Furnitures.Add(furniture);



            if (model.MainImage != null && !model.MainImage.Id.HasValue)
            {
                FurnitureImages image = new FurnitureImages
                {
                    Path = model.MainImage.Path,
                    DisplayName = model.MainImage.DisplayName,
                    IsMainImage = true
                };
                db.FurnitureImages.Add(image);
                db.Entry(furniture).State = EntityState.Added;


            }


            IEnumerable<ImageVM> newImages = model.SecondaryImages.Where(x => x.Id == null);

            foreach (ImageVM image in newImages)
            {

                FurnitureImages imagesSecondary = new FurnitureImages
                {

                    DisplayName = image.DisplayName,
                    Path = image.Path,
                    IsMainImage = false
                };
                db.FurnitureImages.Add(imagesSecondary);

            }




            if (!ModelState.IsValid)
            {
                return View(model);

            }


            db.SaveChanges();
          
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", model.CategoryId);
         return RedirectToAction("Index");
        }

       
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           var furniture = db.Furnitures.Find(id);
            IEnumerable<FurnitureImages> images = furniture.Images;
            if (furniture == null)
            {
                return HttpNotFound();
            }
            FurnitureImages mainImage = images.Where(x => x.IsMainImage).FirstOrDefault();
            IEnumerable<FurnitureImages> secondaryImages = images.Where(x => !x.IsMainImage);

            FurnitureVM model = new FurnitureVM()
            {
                Name = furniture.Name,
                Description = furniture.Description,
                Price = furniture.Price,
                Size = furniture.Size,
                IsAvailable = furniture.IsAvailable,
                CategoryId = furniture.CategoryId,
                Manufacturer = furniture.Manufacturer,

                MainImage = new ImageVM
                {
                    Id = mainImage.Id , 
                    Path = mainImage.Path,
                    DisplayName = mainImage.DisplayName,
                    IsMainImage = mainImage.IsMainImage
                    
                },
               

                SecondaryImages = secondaryImages.Select(x => new ImageVM()
                {
                    Id = x.Id,
                    Path  = x.Path , 
                    DisplayName = x.DisplayName
                }).ToList()
                };
                       
                           
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", furniture.CategoryId);
            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FurnitureVM model)
        {
            if (model.MainFile != null && model.MainFile.ContentLength > 0)
            {
                string displayName = model.MainFile.FileName;
                string extension = Path.GetExtension(displayName);
                string fileName = string.Format("{0}{1}", Guid.NewGuid(), extension);
                string path = "/Upload/" + fileName;
                model.MainFile.SaveAs(Server.MapPath( path));
                model.MainImage = new ImageVM() { Path = path, DisplayName = displayName };
            }

          
           foreach (HttpPostedFileBase file in model.SecondaryFiles)
            {
               
                if (file != null && file.ContentLength > 0)
                {
                    string displayName = file.FileName;
                    string extension = Path.GetExtension(displayName);
                    string fileName = string.Format("{0}{1}", Guid.NewGuid(), extension);
                    var path = "/Upload/" + fileName;
                    file.SaveAs(Server.MapPath(path));
                    model.SecondaryImages.Add(new ImageVM { Path = path, DisplayName = displayName });
                }
            }

            if (!ModelState.IsValid)
            {
                model.CategoryList = new SelectList(db.Categories, "CategoryId", "Name"); // repopulate the SelectList
                return View(model);
            }

            Furniture furniture = db.Furnitures.Where(x => x.FurnitureId == model.ID).FirstOrDefault();
            FurnitureImages main = furniture.Images.Where(x => x.IsMainImage).FirstOrDefault();
            furniture.Name = model.Name;
            furniture.Description = model.Description;
            furniture.Manufacturer = model.Manufacturer;
            furniture.Price = model.Price;
            furniture.IsAvailable = model.IsAvailable;
            furniture.CategoryId = model.CategoryId;
            furniture.Size = model.Size;       
              main.DisplayName = model.MainImage.DisplayName;
              main.Path = model.MainImage.Path;
              main.IsMainImage = model.MainImage.IsMainImage;
            

          

         

            if (model.MainImage != null && !model.MainImage.Id.HasValue)
            {
                FurnitureImages image = new FurnitureImages
                {
                    Path = model.MainImage.Path,
                    DisplayName = model.MainImage.DisplayName,
                    IsMainImage = true
                };
                furniture.Images.Add(image);
                db.Entry(furniture).State = EntityState.Modified;
                


            }

            // Update secondary images
            IEnumerable<ImageVM> newImages = model.SecondaryImages.Where(x => x.Id == null);

            foreach (ImageVM image in newImages)
            {

                FurnitureImages images = new FurnitureImages
                {

                    DisplayName = image.DisplayName,
                    Path =  image.Path , 
                    IsMainImage = false
                };
                furniture.Images.Add(images);
                
            }
             ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", furniture.CategoryId);


            db.Entry(furniture).State = EntityState.Modified;
            db.SaveChanges();
            TempData["message"] = string.Format("Зміни в товарі \"{0}\" були збережені", model.Name);
            return RedirectToAction("Index");


        }
    

FurnitureStore/Views/Furnitures/Create.cshtml
@model FurnitureStore.ModelView.FurnitureVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
   


    @section Scripts {
    <script type="text/javascript">

        $("#fileUpload").on('change', function () {

            if (typeof (FileReader) != "undefined") {

                var image_holder = $("#image-holder");
                image_holder.empty();

                var reader = new FileReader();
                reader.onload = function (e) {
                    $("<img />", {
                        "src": e.target.result,
                        "width": "300px",
                        "class": "thumb-image"
                    }).appendTo(image_holder);

                }
                image_holder.show();
                reader.readAsDataURL($(this)[0].files[0]);
            } else {
                alert("This browser does not support FileReader.");
            }
        });


    </script>

        
        
        }
    
    
    @using (Html.BeginForm("Create", "Furnitures",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()



        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })



            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, "Категорія", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>


          
            <div class="form-group">
                <div class="col-md-10">
                    @Html.Label("Виберіть головне зображення")
                    @Html.TextBoxFor(m => m.MainFile, new { type = "file", name = "MainFile", id = "fileUpload" })
                </div>
                    <div id="image-holder"> </div>
                    @Html.ValidationMessageFor(m => m.MainFile)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(m => m.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>



                <br />

                @Html.TextBoxFor(m => m.SecondaryFiles, new { type = "file", multiple = "multiple", name = "SecondaryFiles" })
                @Html.ValidationMessageFor(m => m.SecondaryFiles)




                <div class="panel-footer">
                    <input type="submit" value="Збергети" class="btn btn-primary" />
                    @Html.ActionLink("Повернутись до списку", "Index", null, new
           {
               @class = "btn btn-default"
           })
                </div>
            </div>



    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FurnitureStore/Views/Furnitures/Edit.cshtml
@model FurnitureStore.ModelView.FurnitureVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Редагування товару";

}



 
   



   @section Scripts {

<script src="@Url.Content("~/Scripts/methods_ru.js")" type="text/javascript"></script>
<script type="text/javascript">
        $('.deleteItem').click(function (e) {
          
            e.preventDefault();
            var $ctrl = $(this);
            if (confirm('Do you really want to delete this file?')) {
                $.ajax({
                    url: '@Url.Action("DeleteFile")',
                    type: 'POST',
                    data: { Id: $(this).attr('data-Id') }
                }).done(function (data) {
                    if (data.Result == "OK") {
                        $ctrl.closest('li').remove();
                    }
                    else if (data.Result.Message) {
                        alert(data.Result.Message);
                    }
                }).fail(function () {
                    //console.log(data.Message);
                    alert("There is something wrong. Please try again.");
                })

            }
        });
</script>       
   }
    
    <h2 style="text-align:center"><b>Редагування @Model.Name</b></h2>

    @using (Html.BeginForm("Edit", "Furnitures",
        FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()




        <div class="container">
            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryId, "Категорія", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        
                        @Html.CheckBoxFor(m => m.IsAvailable)
                        @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div>

                    <div style="margin-left:50px ; width: auto">
                        @Html.Label("Виберіть головне зображення")

                        @Html.TextBoxFor(m => m.MainFile, new { type = "file" })
                        @Html.ValidationMessageFor(m => m.MainFile)
                    </div>

                    @if (Model.MainImage != null)
                    {

                        @Html.HiddenFor(m => m.MainImage.Id)
                        @Html.HiddenFor(m => m.MainImage.Path)
                        @Html.HiddenFor(m => m.MainImage.DisplayName)
                        @Html.HiddenFor(m => m.MainImage.IsMainImage)

                        <img src="@Url.Content(Model.MainImage.Path)" style="margin-left:100px" width="325" alt="@Model.MainImage.DisplayName" />



                    }

                </div>
                @Html.Label("Виберіть  зображення для галереї")
                @Html.TextBoxFor(m => m.SecondaryFiles, new { type = "file", multiple = "multiple", name = "SecondaryFiles" })
                @Html.ValidationMessageFor(m => m.SecondaryFiles)


                <ul class="attachment">
                    @for (int i = 0; i < Model.SecondaryImages.Count; i++)
                {
                        <li style="display:inline-block;  list-style-type: none">
                            @Html.HiddenFor(m => m.SecondaryImages[i].Id)
                            @Html.HiddenFor(m => m.SecondaryImages[i].Path)
                            @Html.HiddenFor(m => m.SecondaryImages[i].DisplayName)
                            <img src="@Url.Content(Model.SecondaryImages[i].Path)" style="height:300px; width:auto" />
                            <a href="javascript:void(0);" data-id="@Model.SecondaryImages[i].Id" class="deleteItem">X</a>
                        </li>
                    }
                </ul>


                <div class="panel-footer">
                    <input type="submit" value="Збергети" class="btn btn-primary" />
                    @Html.ActionLink("Повернутись до списку", "Index", null, new
               {
                   @class = "btn btn-default"
               })
                </div>
            </div>
        </div>



    }
    
    

FurnitureStore/Views/Furnitures/Index.cshtml
@model IEnumerable<FurnitureStore.Entities.Furniture>

@{
    ViewBag.Title = "Панель адміністратора товарів";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



  

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3>Панель Адміністратора товарів</h3>
        </div>
        <div class="panel-body">
       
            <table class="table table-striped table-condensed table-bordered">

    <tr>
        <th class="text-right">Тип</th>
        <th>Назва</th>
        <th class="text-right">Ціна</th>
        <th class="text-center">Дія</th>
        <th class="text-center">Файли </th>
       
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.Category.Name</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { id = item.FurnitureId })</td>
            <td class="text-right">@item.Price.ToString("#грн")</td>
            
            <td class="text-center">
                @using (Html.BeginForm("Delete", "Furnitures" , new { furntitureId = item.FurnitureId }))
                {
                    @Html.Hidden("FurnitureId", item.FurnitureId)
                    <input type="submit"
                           class="btn btn-default btn-xs"
                           value="Видалити" />
                }
            </td>

            <td>
                @if (item.Images.Count == 0)
                {
                    <span>No File</span>
                }
                else
                {
                    <span>@item.Images.Count() File(s)</span>
                }
            </td>

            </tr>
    }

    </table>
</div>
        <div class="panel-footer">
            @Html.ActionLink("Додати товар", "Create", null,
            new { @class = "btn btn-default" })
        </div>
    </div>





      